### ISSUE TITLE
卡死

### ISSUE THREAD

**Issue by yhy0** [boy-hack/ksubdomain#1]
`		Rate:            5000,
		Domain:          []string{"baidu.com"},
		FileName:        "",
		Resolvers:       defaultDns,
		Output:          "",
		OutputCSV:       false,
		Test:            false,
		NetworkId:       -1,
		ListNetwork:     false,
		Silent:          false,
		TTL:             false,
		Stdin:           false,
		DomainLevel:     1,			// 爆破域名层级,默认爆破一级域名
		SkipWildCard:    true,		// 泛解析跳过
		SubNameFileName: "",
		FilterWildCard:  false,
		TimeOut:         10,
		Retry:           3,`

![image](https://user-images.githubusercontent.com/31311038/140475195-7f46d263-ec31-46aa-acca-ebda4a82ae67.png)

**Comment by hakuQAQ** [comment]
+1，我也卡死了。。。

**Comment by boy-hack** [comment]
试试新版
