### ISSUE TITLE
师傅能不能弄个Go的api接口？

### ISSUE THREAD

**Issue by shadow1ng** [boy-hack/ksubdomain#11]
类似Subfinder Go library
```
buf := bytes.Buffer{}
	err = runnerInstance.EnumerateSingleDomain(context.Background(), "projectdiscovery.io", []io.Writer{&buf})
	if err != nil {
		log.Fatal(err)
	}

	data, err := io.ReadAll(&buf)
```

我看了师傅的代码，目前只支持写入文件。
```
if isWrite {
      .........
}
```

简单点的，可以弄成
```
buf := bytes.Buffer{}
if api{
			_, err = buf.WriteString(msg + "\n")
		}
```

**Comment by boy-hack** [comment]
https://github.com/boy-hack/ksubdomain/blob/dev/dev.md dev分支已完成api调用例子

**Comment by shadow1ng** [comment]
![image](https://user-images.githubusercontent.com/39651966/160964980-7bc9548b-140f-4767-a78a-8f43c4672f58.png)
domain类型改成chan string后,出现报错
无法将 'strings.NewReader(strings.Join(domains, "\n"))' (类型 *Reader) 用作类型 chan string

**Comment by boy-hack** [comment]
https://github.com/boy-hack/ksubdomain/blob/main/runner/runner_test.go
