### ISSUE TITLE
在部分ubuntu vps下运行一直输出省略号

### ISSUE THREAD

**Issue by R1dd1er** [boy-hack/ksubdomain#14]
如图
![图片](https://user-images.githubusercontent.com/48016528/159675929-00b861fa-dc91-49bd-a1ac-d7cca7d59383.png)
一开始以为是ubuntu的问题，但是在腾讯云的ubuntu机子跑能跑的起来，libpcap看起来也是正常的，没有头绪，请求指点一下

**Comment by boy-hack** [comment]
贴一下你的`ifconfig`信息，这种情况一般是获取不到网卡

**Comment by R1dd1er** [comment]
> 贴一下你的`ifconfig`信息，这种情况一般是获取不到网卡，或者在vpn的情况下

![图片](https://user-images.githubusercontent.com/48016528/159857302-67d74db0-2c66-406c-abe0-d54be2a98312.png)
