### ISSUE TITLE
枚举模式好像有些问题

### ISSUE THREAD

**Issue by r00tSe7en** [boy-hack/ksubdomain#18]
枚举模式好像有些问题，试了好几个域名都没结果

ksubdomain e -d google.com

[INFO] Current Version: 1.9.5
[INFO] 读取配置ksubdomain.yaml成功!
[INFO] Use Device: eth0
[INFO] Use IP:10.17.0.5
[INFO] Local Mac: a6:1xxxxxx:17:bf
[INFO] GateWay Mac: fe:0xxxxxx01:01
[INFO] libpcap version 1.9.1 (with TPACKET_V3)
[INFO] Default DNS:[223.5.5.5,223.6.6.6,119.29.29.29,182.254.116.116,114.114.114.115]
[INFO] Domain Count:103744
[INFO] Rate:14696pps
[INFO] FreePort:37357
Success:0 Send:518720 Queue:0 Accept:0 Fail:103744 Elapsed:59s
[INFO] 扫描完毕

自动生成的配置文件
src_ip: 10.17.0.5
device: eth0
src_mac: a6:1xxxxxx:17:bf
dst_mac: fe:0xxxxxx01:01

网卡配置

eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 16x.xx.xx.71  netmask 255.255.240.0  broadcast 16x.xx.xx.255
        inet6 fe8xxxxxxxxxxxxxed:17bf  prefixlen 64  scopeid 0x20<link>
        ether a6:12xxxxxxxxx7:bf  txqueuelen 1000  (Ethernet)
        RX packets 57098586  bytes 21600152403 (21.6 GB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 53186680  bytes 8359693999 (8.3 GB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.108.0.2  netmask 255.255.240.0  broadcast 10.108.15.255
        inet6 fe80xxxxxxxxx823  prefixlen 64  scopeid 0x20<link>
        ether fa:2xxxxxxxxx8:23  txqueuelen 1000  (Ethernet)
        RX packets 2239  bytes 156806 (156.8 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 2286  bytes 160156 (160.1 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**Comment by xcsykb** [comment]
我也是，试了好几个 都没结果，是我们操作问题吗

**Comment by r00tSe7en** [comment]
> 我也是，试了好几个 都没结果，是我们操作问题吗

感觉是获取网卡的问题
