### ISSUE TITLE
docker运行报错

### ISSUE THREAD

**Issue by elagit** [boy-hack/ksubdomain#2]
![image](https://user-images.githubusercontent.com/45376015/154262878-5bd79d7a-3a0c-4f64-8080-bfac79be73a0.png)
bash-5.1# ./ksubdomain 
Error relocating ./ksubdomain: __snprintf_chk: symbol not found
Error relocating ./ksubdomain: __vfprintf_chk: symbol not found
Error relocating ./ksubdomain: getnetbyname_r: symbol not found
Error relocating ./ksubdomain: __asprintf_chk: symbol not found
Error relocating ./ksubdomain: __memcpy_chk: symbol not found
Error relocating ./ksubdomain: __vsnprintf_chk: symbol not found
Error relocating ./ksubdomain: __fread_chk: symbol not found
Error relocating ./ksubdomain: __longjmp_chk: symbol not found
Error relocating ./ksubdomain: __memset_chk: symbol not found
Error relocating ./ksubdomain: __fprintf_chk: symbol not found
Error relocating ./ksubdomain: getprotobyname_r: symbol not found

docker运行报错

image python:3.8-alpine
Linux aa9ec1622559 5.4.0-90-generic #101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021 x86_64 Linux

是缺什么依赖么

**Comment by boy-hack** [comment]
用ubuntu的镜像试试呢，alpine太精简了

**Comment by elagit** [comment]
ok
