### ISSUE TITLE
请教作者命令使用是否正确

### ISSUE THREAD

**Issue by sv3nbeast** [boy-hack/ksubdomain#22]
场景:拥有一批二级域名，想跑三级域名
命令:./ksubdomain e --domainList domain.txt --silent -f dic/subdomains_long.txt -l 3 -o result.txt
你好，请问这样会用字典去跑字典里的二级域名的三级域名吗，想直接请教一下作者。

**Comment by boy-hack** [comment]
不需要-l 直接这样即可
```
./ksubdomain e --domainList domain.txt --silent -f dic/subdomains_long.txt -o result.txt
```

**Comment by sv3nbeast** [comment]
发现域名过多时会爆内存错误，三级域名爆破这个命令貌似会得到二级域名，具体是我的还是命令的问题没有深追，期待后续的更新，感谢提供的工具
