### ISSUE TITLE
内存泄漏

### ISSUE THREAD

**Issue by hktalent** [boy-hack/ksubdomain#31]
<img width="1194" alt="Screenshot 2023-01-28 at 20 53 04" src="https://user-images.githubusercontent.com/18223385/215267390-80e2dc0c-7625-41f7-972e-8cf509cd7d76.png">
<img width="488" alt="Screenshot 2023-01-28 at 20 53 48" src="https://user-images.githubusercontent.com/18223385/215267410-81ecb919-4f8b-478c-ba61-8068adccdc36.png">

**Comment by imkitsch** [comment]
请问这个问题你解决了吗，可以分享一下吗
