### ISSUE TITLE
Ksubdomain无结果

### ISSUE THREAD

**Issue by li-baige** [boy-hack/ksubdomain#34]
环境：Docker部署的Alpine系统，该容器同时还部署了其他工具，但是只有ksubdomain无结果，情况如下：
<img width="854" alt="截屏2023-05-21 16 32 16" src="https://github.com/boy-hack/ksubdomain/assets/76275424/baa38163-8011-4a2a-8eb6-c1a62803f2b6">
这个版本有问题还是对ARM for Linux的支持不好，问题无法解决，请求作者帮助。

**Comment by HiIK-666** [comment]
adm 同问题

**Comment by boy-hack** [comment]
尝试最新版
