### ISSUE TITLE
Mac m2 运行报错

### ISSUE THREAD

**Issue by Layjb** [boy-hack/ksubdomain#37]
执行语句 ：./ksubdomain e -d xxx.com
报错内容：
循环：
[Warning] WritePacketDate error:send: Bad file descriptor
[Warning] WritePacketDate error:send: Bad file descriptor
[Warning] WritePacketDate error:send: Bad file descriptor
[Warning] WritePacketDate error:send: Bad file descriptor
[Warning] WritePacketDate error:send: Bad file descriptor
[Warning] WritePacketDate error:send: Bad file descriptor
[Warning] WritePacketDate error:send: Bad file descriptor
[Warning] WritePacketDate error:send: Bad file descriptor
[Warning] WritePacketDate error:send: Bad file descriptor

**Comment by boy-hack** [comment]
尝试最新版，支持mac arm
