### ISSUE TITLE
内存消耗大，是否可以优化一下

### ISSUE THREAD

**Issue by r0ckysec** [boy-hack/ksubdomain#6]
![截屏2022-02-21 18 39 57](https://user-images.githubusercontent.com/44518337/154939252-5c2e7166-2a7a-405c-87f5-cac61cebab81.png)

**Comment by boy-hack** [comment]
多大内存的机器和多大的字典呢？ 内部有建立状态表会需要耗费一些内存

**Comment by r0ckysec** [comment]
字典40w左右吧，扫100个域名，机器内存我设了10G的交换，中间稳定的时候 ksubdomain占了7g的交换内存，然后如果还想开一个任务就会炸掉，或跑不起来

**Comment by boy-hack** [comment]
最好是扫一个域名起一个进程，扫完了再进行下一个，这样占用应该不会那么大了
